### PR TITLE
Bump wlroots to 0.12.x and remove xdg-shell-unstable-v6

### PR DESCRIPTION
**Pull request by psnszsn**

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Thanks!

**Comment by emersion** [comment]
Hm, sounds like the build fails: https://builds.sr.ht/~emersion/job/358648#task-build

**Comment by psnszsn** [comment]
> Hm, sounds like the build fails: https://builds.sr.ht/~emersion/job/358648#task-build

The build succeeds with wlroots 0.12.0 but not master.

**Comment by emersion** [comment]
Can we fix master?

**Comment by psnszsn** [comment]
Sure, i'll look into it.

**Pull request merged**
